# Generated by Django 4.2.7 on 2023-12-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('coding', 'Coding'), ('music', 'Music'), ('art', 'Art')], default='coding', max_length=255),
        ),
    ]
